import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Learning Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col bg-slate-500 text-white h-screen`}
      >
        <Navbar />

        <div className="flex-grow">{children}</div>

        <footer className="bg-slate-800 p-5 text-center">
          <p>This is footer</p>
        </footer>
      </body>
    </html>
  );
}
